spring:
  application:
    name: interview-ai-backend

  profiles:
    default: local

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

server:
  port: 8080

auth:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: 1h
    refresh-token-expiration: 14d

management:
  endpoints:
    web:
      exposure:
        include: health, info
